### ISSUE TITLE
On footer side, the social media will disappear when we will scroll down the page.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Ramfa-due-on-22-Jan#1]
**Actual result:**
On footer side, the social media will disappear when we will scroll down the page.
![image](https://user-images.githubusercontent.com/102131636/168573649-083ecf3a-1cb7-46a7-b764-82699be9e447.png)

**Expected result:**
The social media link icon have to be visible properly when we scroll down the page.

**Comment by ui-amankumar** [comment]
@sudhanshu0603 done

**Comment by sudhanshu0603** [comment]
ok, resolved
