### ISSUE TITLE
When we are searching any product then the  along with the count of product - symbol is coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Ramfa-due-on-22-Jan#2]
**Actual result:**
When we are searching any product then the  along with the count of product - symbol is coming.
![image](https://user-images.githubusercontent.com/102131636/168575324-47898bb0-3db1-49c7-b51f-12ae932289b5.png)

**Expected result:**
The - symbol can be removed or can be aligned in the middle along with the text product it will be much better.

**Comment by ui-amankumar** [comment]
@sudhanshu0603 done
