### ISSUE TITLE
The count of the product is coming 35 but many products are coming on scrolling.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Ramfa-due-on-22-Jan#3]
**The url:**
https://ramfabeauty.com/collections/all-fragrance
**Actual result:**
The count of the product is coming 35 but many products are coming on scrolling.
![image](https://user-images.githubusercontent.com/102131636/168586069-ba2a39d6-ec7d-4405-82ab-36b2c117f934.png)
![image](https://user-images.githubusercontent.com/102131636/168586126-d36b06f7-1418-4f9e-a53c-c3935dfe9a4d.png)
**The video issue:**
https://www.awesomescreenshot.com/video/8923987?key=7777ea6434536a41e293ef2892f065b7
**Expected result:**
The count of the products and the total product for the collection have to be same.

**Comment by devSuneel** [comment]
It displays the total product count per page

**Comment by sudhanshu0603** [comment]
ok, resolved
