### ISSUE TITLE
When we hover over the filter options ( Checkout box  ) then hand cursor have to come.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Ramfa-due-on-22-Jan#5]
**The url:**
https://ramfabeauty.com/collections/all-fragrance
**Actual result:**
When we hover over the filter options ( Checkout box  ) then hand cursor have to come.
![image](https://user-images.githubusercontent.com/102131636/168588108-fb0ae136-f2f6-4d60-a604-88b8cdc2a0e2.png)

**Expected result:**
The hand cursor have to come when we hover over the checkout box.

**Comment by ui-amankumar** [comment]
@sudhanshu0603 done

**Comment by sudhanshu0603** [comment]
ok, resolved
