### ISSUE TITLE
When we click on the suggested email for the newsletter then the text will not be visible.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Ramfa-due-on-22-Jan#8]
**Actual result:**
When we click on the suggested email for the newsletter then the text will not be visible.
![image](https://user-images.githubusercontent.com/102131636/168766083-b7193ef6-f562-46b9-8ece-9eb8b2980bce.png)

**The video issue:**
https://www.awesomescreenshot.com/video/8941350?key=1a5150b9896907c1e7709220eccbfa78

**Expected result:**
The text of the email have to be visible when we are selecting the suggested email.

**Comment by ui-amankumar** [comment]
@sudhanshu0603 done
