### ISSUE TITLE
In cart page, the continue shopping text is not coming in the centre

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Ramfa-due-on-22-Jan#9]
**Actual result:**
In cart page, the continue shopping text is not coming in the centre.
![image](https://user-images.githubusercontent.com/102131636/168776655-c8fce16b-e8b0-4dd4-ba78-b13bfcdaa0e3.png)

**Expected result:**
The text continue shopping have to come in the centre it will be much better.

**Comment by ui-amankumar** [comment]
@sudhanshu0603 done

**Comment by sudhanshu0603** [comment]
ok, resolved
